apiVersion: v1
kind: PersistentVolume
metadata:
  name:  xkcoding-pv
  namespace: xkcoding
spec:
  capacity: 
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s
    server: 192.168.0.5